trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Pay-As-You-Go'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build -t mydemorepo.azurecr.io/todo:tag new_repo
      az acr login -n mydemorepo
      docker push mydemorepo.azurecr.io/todo:tag

- script: cat 01_kubernetes_aks/app-deploy.yaml

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Pay-As-You-Go'
    azureResourceGroup: 'demotest'
    kubernetesCluster: 'mydemoclus'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: '01_kubernetes_aks'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'Pay-As-You-Go'
    azureContainerRegistry: 'mydemorepo.azurecr.io'
    forceUpdate: false
